baseURL = 'https://ezcan.github.io/candojo/'
languageCode = 'zh-TW'
title = 'Candojo'
theme = 'PaperMod'
enableInlineShortcodes = true

[params]
  env = "production"
  ShowCodeCopyButtons = true
  ShowShareButtons = true